### ISSUE TITLE
reboot by itself to config mode

### ISSUE THREAD

**Issue by te260701** [ChipTechno/WiFiMan#11]
Hi Chip,

I have an issue esp8266 reboot into AP config mode by itself and it seem never get out of it even after portal timeout (maybe I'm wrong). I have to manually press reset button or connect to AP and click reset to get it working again. 

It is weird. It lost reboot at 11:58pm everyday and sometime can reconnect but most of the time it cannot. Wifi was working fine when it reboot.

Is there a way to reboot normally (autoconnect) after config portal timeout?

Thank you,
Sam

**Comment by ChipCE** [comment]
By default, the device will auto connect to WiFi with saved config.
What version of esp8266 are you using? This library heavily depends on flash memory space, it may not save config on some low flash esp8266(esp01 for example).
Can you provide the debug log, please?

**Comment by te260701** [comment]
Hi Chip,

It was my bad. There is bug in my code that call for a function that doesnt exist.

Thank you for your very fast reply,
