### ISSUE TITLE
Captive portal broken on Apple devices

### ISSUE THREAD

**Issue by DanTheMan827** [ChipTechno/WiFiMan#20]
If you respond to all dns queries with the IP of the config portal, devices would automatically show it when they connect.

**Comment by DanTheMan827** [comment]
I see you do just that, but for whatever reason the configuration isn't showing on an iPhone, with the Tasmota firmware the config page appears right away.

**Comment by ChipCE** [comment]
@DanTheMan827  If I remember correctly. The portal won't show up if you have password enabled?

**Comment by DanTheMan827** [comment]
The HTTP response cannot be 404, for Apple it has to do a 302 redirect.

**Comment by ChipCE** [comment]
Thank you!
Your patch will be included in the next release after I clean up some other code.
